### ISSUE TITLE
Erroneous name in gb sources

### ISSUE THREAD

**Issue by lukeplatts** [davidam/damegender#29]
https://github.com/davidam/damegender/blob/b1ac72d2c30e34df44ef2ec4227531002cef3085/src/damegender/files/names/names_gb/gbsurnames.csv?plain=1#L17777

**Comment by davidam** [comment]
Hello Luke!

Thanks for the feedback. Take into account that the official sources is in config.cfg. So the official datasets (retrieved from statistical sources) about surnames is 
official_surnames = ["ar", "es", "ru", "us"]
That's Argentina, Spain, Russia and United States of America.
The file gbsurnames.csv was downloaded with get-wikidata-surnames.py. I'm going to check the trouble, but you can consider to use files/names/names_us/surnames.csv if you need surnames in english.

Happy hacking!

**Comment by davidam** [comment]
I've fixed the file.
And now, you can check long strings in the csv DameGender files. For example:
$ python3 checkcsv.py --first_name_position=0 names.csv --verbose

So, if you want to use the script or the csv, you must clone DameGender or to wait to a new release.
Good luck!
