### ISSUE TITLE
Proposal to change the structure of files and directories and new features

### ISSUE THREAD

**Issue by KOLANICH** [davidam/damegender#7]
In the current state the repo looks like a complete mess. Please structure it the way so different things:

* datasets
* models
* interfaces to APIs
* backends
* CLI tools
* misc utility code 

are localized in different dirs and write some guide for newcomers.

I also would be glad to know where I can download state of the art datasets (pretrained models are fine too) giving answers (or which can be used to create models giving answers) to the following questions:

* given a word N, what is the probability it is a given name
* given a word N, what is the probability it is a surname
* given a word N, what is the probability it is not any part of a name at all
* given a word N, what is the probability it is a middle name
* given an allegedly given name N and a surname S, what is the probability that a name and a surname have been swapped and what is that they are not names at all (can be derived using Bayes formula from 4 previous results)
* given a name and a surname predict distribution of nationalities of the bearer
* given a name and a surname in a non-canonical form (i.e. translit), get a canonical form (name and surname in its native language, as in ID/passport)

**Comment by davidam** [comment]
Thanks for your interest in Damegender. There are not plans about change the structure, but you can read the manual, watch videos, read papers, or read the faq to learn to use the software. Please, visit http://damegender.davidam.com/#documentation

All datasets about names is in files/names, the models pretrained are in files/datamodels

You can detect a word as a name using the next command:
$ python3 main.py word --total=inter
But the software is not designed in the current state for assigning probabilities to words to guess if it is a name or not. We are in the situation about you have a word that you think that is a name and you try imagine if it's about a male or a female and what is the probability. If you are interested on pay this feature you can write me on private about it.

The current state about detection about nationalities could be improved, we are giving nameincountries.py and surnameincountries.py

Tell me about your interest on pay by the development, with another ideas I would give this issue as closed.

**Comment by KOLANICH** [comment]
Thank you for the info!
